# Generated by Django 5.0 on 2023-12-15 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='begin_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 10, 50, 58, 308854, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 12, 50, 58, 308854, tzinfo=datetime.timezone.utc)),
        ),
    ]
