# Generated by Django 5.0 on 2023-12-15 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_poll_begin_date_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='begin_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 11, 10, 18, 841296, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 13, 10, 18, 841296, tzinfo=datetime.timezone.utc)),
        ),
    ]
